export const BD_LOCATIONS: Record<string, string[]> = {
  "Dhaka": ["Dhanmondi", "Gulshan", "Mirpur", "Mohammadpur", "Motijheel", "Uttara", "Banani", "Bashundhara", "Khilgaon", "Shyamoli", "Farmgate", "Tejgaon"],
  "Chattogram": ["Agrabad", "Halishahar", "Pahartali", "Kotwali", "Double Mooring", "Bakalia", "Chandgaon", "Panchlaish"],
  "Rajshahi": ["Boalia", "Motihar", "Shah Mukdum", "Paba"],
  "Khulna": ["Boyra", "Daulatpur", "Khalishpur", "Khan Jahan Ali", "Sonadanga", "Harintana"],
  "Barishal": ["Airport", "Kawnia", "Bangabandhu", "Nobogram"],
  "Sylhet": ["Airport", "Mugda", "Khadimnagar", "Kotwali"],
  "Rangpur": ["Momin Road", "Station Road", "Keranipara", "Joshore Road"],
  "Mymensingh": ["Kachijhuli", "Shombhuganj", "Muktijoddha Road", "Sadar"],
  "Comilla": ["Kandirpar", "Moullavita", "Shashongachi", "Sadar"],
  "Narayanganj": ["Bandar", "Fatullah", "Siddhirganj", "Jalkuri"],
  "Gazipur": ["Tongi", "Kaliakoir", "Sreepur", "Kapasia"],
  "Bogra": ["Sadar", "Gabtali", "Shibganj", "Sonatala"],
  "Jessore": ["Sadar", "Chaugachha", "Jhikargachha", "Monirampur"],
  "Cox's Bazar": ["Sadar", "Ramu", "Teknaf", "Ukhia"],
  "Kushtia": ["Sadar", "Kumarkhali", "Bheramara", "Mirpur"],
  "Tangail": ["Sadar", "Mirzapur", "Gopalpur", "Kalihati"],
  "Faridpur": ["Sadar", "Nagarkanda", "Bhanga", "Alfadanga"],
  "Natore": ["Sadar", "Naldanga", "Singra", "Bagatipara"],
  "Dinajpur": ["Sadar", "Birampur", "Kaharole", "Bochaganj"],
  "Pabna": ["Sadar", "Sujanagar", "Ishwardi", "Bera"],
  "Jamalpur": ["Sadar", "Dewanganj", "Melandaha", "Madarganj"],
  "Sherpur": ["Sadar", "Nalitabari", "Sreebardi", "Jhenaigati"],
  "Netrokona": ["Sadar", "Kendua", "Atpara", "Barhatta"],
  "Kishoreganj": ["Sadar", "Bhairab", "Hossainpur", "Karimganj"],
  "Sunamganj": ["Sadar", "Chhatak", "Derai", "Dirai"],
  "Habiganj": ["Sadar", "Nabiganj", "Chunarughat", "Madhabpur"],
  "Brahmanbaria": ["Sadar", "Kasba", "Sarail", "Ashuganj"],
  "Chandpur": ["Sadar", "Matlab", "Hajiganj", "Kachua"],
  "Lakshmipur": ["Sadar", "Ramganj", "Ramgati", "Raipur"],
  "Feni": ["Sadar", "Daganbhuiyan", "Sonagazi", "Parshuram"],
  "Noakhali": ["Sadar", "Begumganj", "Chatkhil", "Senbagh"],
  "Bhola": ["Sadar", "Borhanuddin", "Daulatkhan", "Char Fasson"],
  "Patuakhali": ["Sadar", "Dumki", "Bauphal", "Mirzaganj"],
  "Pirojpur": ["Sadar", "Nazirpur", "Kawkhali", "Bhandaria"],
  "Jhalokati": ["Sadar", "Rajapur", "Nalchity", "Kathalia"],
  "Barguna": ["Sadar", "Amtali", "Betagi", "Patharghata"],
  "Satkhira": ["Sadar", "Assasuni", "Kalaroa", "Tala"],
  "Magura": ["Sadar", "Shalikha", "Mohammadpur"],
  "Jhenaidah": ["Sadar", "Harinakunda", "Shailkupa", "Kotchandpur"],
  "Chuadanga": ["Sadar", "Alamdanga", "Damurhuda", "Jibannagar"],
  "Meherpur": ["Sadar", "Gangni", "Mujibnagar"],
  "Narail": ["Sadar", "Lohagara", "Kalia"],
  "Gopalganj": ["Sadar", "Kashiani", "Tungipara", "Muksudpur"],
  "Madaripur": ["Sadar", "Kalkini", "Rajoir", "Shibchar"],
  "Shariatpur": ["Sadar", "Damudya", "Naria", "Janjira"],
  "Manikganj": ["Sadar", "Saturia", "Shibalaya", "Singair"],
  "Munshiganj": ["Sadar", "Tongibari", "Sreenagar", "Lohajang"],
  "Rajbari": ["Sadar", "Goalanda", "Pangsha", "Kalukhali"],
  "Narsingdi": ["Sadar", "Palash", "Shibpur", "Belabo"],
  "Sirajganj": ["Sadar", "Shahjadpur", "Ullapara", "Kamarkhanda"],
  "Naogaon": ["Sadar", "Mandas", "Badalgachhi", "Patnitala"],
  "Joypurhat": ["Sadar", "Khetlal", "Panchbibi", "Akkelpur"],
  "Gaibandha": ["Sadar", "Sundarganj", "Palashbari", "Sadullapur"],
  "Kurigram": ["Sadar", "Nageshwari", "Ulipur", "Chilmari"],
  "Lalmonirhat": ["Sadar", "Hatibandha", "Patgram", "Kaliganj"],
  "Nilphamari": ["Sadar", "Saidpur", "Jaldhaka", "Domar"],
  "Panchagarh": ["Sadar", "Tetulia", "Debiganj", "Boda"],
  "Thakurgaon": ["Sadar", "Baliadangi", "Haripur", "Ranishankail"],
  "Bandarban": ["Sadar", "Ruma", "Thanchi", "Lama"],
  "Khagrachari": ["Sadar", "Matiranga", "Ramgarh", "Manikchhari"],
  "Rangamati": ["Sadar", "Kaptai", "Kawkhali", "Naniarchar"],
  "Moulvibazar": ["Sadar", "Sreemangal", "Kulaura", "Barlekha"]
};
