-- Supabase Database Schema for SNEHALATA-Ecosystem (V2.0)
-- 1. Create categories table (Admin Managed)
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    description TEXT,
    icon TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enhance Vendors table for Lifecycle
CREATE TABLE IF NOT EXISTS public.vendors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id UUID REFERENCES auth.users(id), -- Linked to Supabase Auth
    store_name TEXT NOT NULL,
    owner_name TEXT,
    email TEXT UNIQUE,
    status TEXT DEFAULT 'PENDING', -- PENDING, APPROVED, SUSPENDED
    category_id BIGINT REFERENCES public.categories(id),
    website_url TEXT,
    description TEXT,
    logo_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    metadata JSONB DEFAULT '{}'::jsonb
);

-- 3. Enhance Products for Real Tracking
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id BIGINT REFERENCES public.vendors(id),
    name TEXT NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    category TEXT,
    image_url TEXT,
    description TEXT,
    external_url TEXT, -- Source URL from scraping
    is_verified BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Enable RLS
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- 5. Policies
CREATE POLICY "Public Read Categories" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Public Read Vendors" ON public.vendors FOR SELECT USING (status = 'APPROVED');
CREATE POLICY "Public Read Products" ON public.products FOR SELECT USING (true);

-- Vendor Specific Policies
CREATE POLICY "Vendors Can Update Own Profile" ON public.vendors 
    FOR UPDATE USING (auth.uid() = owner_id);
CREATE POLICY "Vendors Can Manage Own Products" ON public.products 
    FOR ALL USING (vendor_id IN (SELECT id FROM public.vendors WHERE owner_id = auth.uid()));

-- 6. Initial Data
INSERT INTO public.categories (name, slug, description, icon)
VALUES 
    ('Jamdani Heritage', 'jamdani-heritage', 'Authentic hand-loomed creations.', 'Tag'),
    ('Urban Streetwear', 'urban-streetwear', 'Modern Dhaka-inspired fashion.', 'Zap'),
    ('Fusion Wear', 'fusion-wear', 'Western silhouettes with local textiles.', 'Camera')
ON CONFLICT (slug) DO NOTHING;
